SELECT top 100 FT_TBL.id,FT_TBL.name,FT_TBL.code,FT_TBL.cat1_id,FT_TBL.cat2_id,FT_TBL.cat3_id,FT_TBL.cat4_id,FT_TBL.views, 
RANK=CASE FT_TBL.cat2_id WHEN 7 THEN KEY_TBL.RANK*7 WHEN 18 THEN KEY_TBL.RANK*6 WHEN 15 THEN KEY_TBL.RANK*5 WHEN 5 THEN 
KEY_TBL.RANK*4 WHEN 23 THEN KEY_TBL.RANK*3 WHEN 6 THEN KEY_TBL.RANK*2 ELSE KEY_TBL.RANK END 
FROM documents AS FT_TBL INNER JOIN FREETEXTTABLE(documents, auto_des,'cấp giấy chứng nhận quyền sử dụng đất') AS 
KEY_TBL ON FT_TBL.id = KEY_TBL.[KEY]  where (RANK>0)  order by RANK Desc