//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlvb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class document_items
    {
        public int id { get; set; }
        public Nullable<int> document_id { get; set; }
        public string item_id { get; set; }
        public string item_content { get; set; }
    }
}
