//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qlvb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class document
    {
        public int id { get; set; }
        public string name { get; set; }
        public string auto_des { get; set; }
        public string code { get; set; }
        public string keyword1 { get; set; }
        public string keyword2 { get; set; }
        public string keyword3 { get; set; }
        public Nullable<int> cat1_id { get; set; }
        public Nullable<int> cat2_id { get; set; }
        public Nullable<int> cat3_id { get; set; }
        public Nullable<int> cat4_id { get; set; }
        public Nullable<byte> type { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string related_id { get; set; }
        public Nullable<int> year { get; set; }
        public string link { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<int> views { get; set; }
    }
}
